language: node_js
node_js:
  - "node"
services:
  - postgresql
before_install:
  - cd backend
before_script:
  - psql < data.sql
install:
  - npm install  
  - npm install --save-dev jest
script:
- npm test
env:
  - NODE_ENV=test